### ISSUE TITLE
go.mod issue

### ISSUE THREAD

**Issue by perbu** [borud/broker#3]
Hi Bjørn.

I suspect there is an issue with the go.mod. Trying to import it I get:
```
	github.com/borud/broker/v2: module github.com/borud/broker@latest found (v1.0.2), but does not contain package github.com/borud/broker/v2
```

For 2.0 modules you need to declare the modules as a v2 package in go.mod.

Fixed in  #4

**Comment by borud** [comment]
I'd rather not use the /v2 mechanism as it tends to confuse IDEs.  Visual Studio Code constantly confuses v2 and non-v2 imports and there doesn't seem to be a good solution for this.  You can still control the version of dependencies in applications by specifying the version in the go.mod file where the broker lib is used

```
require (
        github.com/borud/broker v2.0.0
)
```

If you think it is important to use /v2 we have to do a bit more work than just change the go.mod file.  We'd have to go back and revert the root dir version to pre v2.0.0, make a subdirectory called v2, add a go.mod file to it and then put the new (v2.0.0) code in that directory.
